const $ = id => document.getElementById(id);
let currentStatus = null;
function text(id, value) { $(id).textContent = value == null || value === '' ? '—' : value; }
function ms(value) { return value == null ? '—' : `${value} ms`; }
function toast(message) { text('toast', message); $('toast').classList.add('show'); setTimeout(() => $('toast').classList.remove('show'), 4500); }
async function api(path, body) { const response = await fetch(`/api/${path}`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body || {})}); const data = await response.json(); if(!response.ok) throw new Error(data.error?.message || 'Request failed'); return data; }
function render(status) { currentStatus=status; const m=status.machine,a=status.audio,w=status.whisper,an=status.anyModel,ad=status.android,r=status.risk;
 text('windows',m.windows); text('bluetooth',m.bluetooth); text('phone-link',m.phoneLink); text('tailscale',status.tailscale); text('audio-state',a.state); text('audio-strategy',a.strategy); text('whisper',w.selfTest || 'NOT RUN'); text('whisper-device',w.device || 'CPU'); text('anymodel',an.state); text('decision-source',r.source); text('android',ad.status); text('permissions',ad.devices?.[0] ? JSON.stringify(ad.devices[0].permissions) : 'NOT REPORTED'); text('alert-latency',ms(status.metrics.alertDeliveryMs)); text('stt',ms(status.metrics.sttMs)); text('decision-ms',ms(status.metrics.localDecisionMs)); text('ack-ms',ms(status.metrics.alertDeliveryMs)); text('transcript',status.transcript === '-' ? 'No stable caller utterance yet.' : status.transcript); text('risk',r.level); text('risk-reason',r.reason); $('protection-heading').dataset.risk=r.level; text('mode-chip',status.mode); const selected=a.selected; text('capture-final',a.state || 'NOT TESTED'); text('capture-selected',selected?.processName); text('capture-pid',selected?.pid); text('capture-rms',selected?.rms); text('capture-peak',selected?.peak); text('capture-attempts',(a.candidates || []).map(x=>`${x.processName}   ${x.state}`).join('\n') || 'Use Test Call Capture to inspect current Phone Link processes.'); $('play-recording').disabled=!selected; document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===status.mode))); const list=$('events'); list.replaceChildren(...status.events.slice().reverse().map(e=>{const li=document.createElement('li');li.textContent=`${e.at}  ${e.type}  ${e.detail}`;return li;})); }
async function refresh(){try{render(await fetch('/api/status',{cache:'no-store'}).then(r=>r.json()));}catch(e){toast('Backend unavailable: '+e.message)}}
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',async()=>{try{render(await api('mode',{mode:button.dataset.mode}));toast(`Mode: ${button.dataset.mode}`)}catch(e){toast(e.message)}}));
$('transcript-form').addEventListener('submit',async e=>{e.preventDefault();const input=$('transcript-input');try{const out=await api('transcripts',{text:input.value});toast(`${out.risk}: ${out.reason}`);input.value='';await refresh()}catch(e){toast(e.message)}});
document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',async()=>{try{let out;if(button.dataset.action==='pair'){out=await api('pair');$('pairing-payload').textContent=JSON.stringify(out,null,2);toast('Pairing payload created; it expires in five minutes.')}else{out=await api(button.dataset.action,button.dataset.action==='diagnostics/capture'?{source:'EXPLICIT_TEST_BUTTON'}:{});toast(out.detail || out.state || 'Completed');}await refresh()}catch(e){toast(e.message)}}));
$('play-recording').addEventListener('click',()=>{const audio=new Audio('/api/diagnostics/recording');audio.play().catch(e=>toast('Playback failed: '+e.message));});
function connect(){const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);ws.onopen=()=>{ $('socket-dot').classList.add('on');text('socket-label','LIVE');ws.send(JSON.stringify({type:'subscribe'}));};ws.onmessage=e=>{try{const data=JSON.parse(e.data);if(data.status) render(data.status);if(data.type==='alert')toast(`ANDROID ALERT: ${data.message}`)}catch{}};ws.onclose=()=>{$('socket-dot').classList.remove('on');text('socket-label','RECONNECTING');setTimeout(connect,1500)};ws.onerror=()=>ws.close();}refresh();connect();setInterval(refresh,5000);
