"""Stable localized Hybrid V1 reason-code templates; no generative explanation path."""
from __future__ import annotations

TEMPLATES = {
    "en": {"OTP_REQUESTED": "The caller asked for a verification code.", "MONEY_TRANSFER_REQUESTED": "The caller asked you to move money.", "REMOTE_ACCESS_REQUESTED": "The caller requested remote device access.", "REQUEST_OPEN_LINK": "The caller asked you to open a link or QR code.", "REQUEST_CRYPTO_TRANSFER": "The caller requested a crypto or gift-card transfer.", "REQUEST_CASH_TO_COURIER": "The caller requested cash for a courier.", "IDENTITY_BANK_CLAIMED": "The caller claimed to represent a bank.", "URGENCY_DETECTED": "The caller applied time pressure.", "SECRECY_REQUESTED": "The caller requested secrecy.", "KEEP_CALL_ACTIVE_DETECTED": "The caller asked you to stay on the call.", "VERIFYING_DISCOURAGED": "The caller discouraged independent verification.", "PROTECTIVE_ADVICE_DETECTED": "Protective advice was detected."},
    "ro": {"OTP_REQUESTED": "Interlocutorul a solicitat un cod de confirmare.", "MONEY_TRANSFER_REQUESTED": "Interlocutorul a solicitat mutarea banilor.", "REMOTE_ACCESS_REQUESTED": "Interlocutorul a solicitat acces la distanță.", "REQUEST_OPEN_LINK": "Interlocutorul a cerut deschiderea unui link sau cod QR.", "REQUEST_CRYPTO_TRANSFER": "Interlocutorul a solicitat un transfer cripto sau card cadou.", "REQUEST_CASH_TO_COURIER": "Interlocutorul a solicitat numerar pentru curier.", "IDENTITY_BANK_CLAIMED": "Interlocutorul a pretins că reprezintă o bancă.", "URGENCY_DETECTED": "Interlocutorul a aplicat presiune de timp.", "SECRECY_REQUESTED": "Interlocutorul a cerut păstrarea secretului.", "KEEP_CALL_ACTIVE_DETECTED": "Interlocutorul a cerut să rămâneți la telefon.", "VERIFYING_DISCOURAGED": "Interlocutorul a descurajat verificarea independentă.", "PROTECTIVE_ADVICE_DETECTED": "A fost detectat un sfat de protecție."},
    "ru": {"OTP_REQUESTED": "Собеседник попытался получить код подтверждения.", "MONEY_TRANSFER_REQUESTED": "Собеседник попросил перевести деньги.", "REMOTE_ACCESS_REQUESTED": "Собеседник запросил удалённый доступ к устройству.", "REQUEST_OPEN_LINK": "Собеседник попросил открыть ссылку или QR-код.", "REQUEST_CRYPTO_TRANSFER": "Собеседник запросил криптоперевод или подарочную карту.", "REQUEST_CASH_TO_COURIER": "Собеседник попросил передать наличные курьеру.", "IDENTITY_BANK_CLAIMED": "Собеседник представился сотрудником банка.", "URGENCY_DETECTED": "Собеседник оказывает давление срочностью.", "SECRECY_REQUESTED": "Собеседник просит сохранить информацию в тайне.", "KEEP_CALL_ACTIVE_DETECTED": "Собеседник просит не завершать звонок.", "VERIFYING_DISCOURAGED": "Собеседник препятствует независимой проверке.", "PROTECTIVE_ADVICE_DETECTED": "Обнаружен защитный совет."},
}

def explain(reason_codes: list[str], language: str) -> list[str]:
    table = TEMPLATES.get(language, TEMPLATES["en"])
    return [table.get(code, TEMPLATES["en"].get(code, "Social-engineering indicators were detected.")) for code in reason_codes]
