// Emits raw 48 kHz stereo PCM to stdout only when the Redmi/Audiosrv sentinel is active.
#include <windows.h>
#include <mmdeviceapi.h>
#include <audioclient.h>
#include <audiopolicy.h>
#include <string>
#include <vector>
static bool sentinel(IMMDeviceEnumerator* e){IMMDeviceCollection*c=0;e->EnumAudioEndpoints(eRender,DEVICE_STATEMASK_ALL,&c);UINT n=0;if(c)c->GetCount(&n);bool found=false;for(UINT i=0;i<n;i++){IMMDevice*d=0;c->Item(i,&d);IAudioSessionManager2*m=0;if(d&&SUCCEEDED(d->Activate(__uuidof(IAudioSessionManager2),CLSCTX_ALL,0,(void**)&m))){IAudioSessionEnumerator*s=0;if(SUCCEEDED(m->GetSessionEnumerator(&s))){int q=0;s->GetCount(&q);for(int j=0;j<q;j++){IAudioSessionControl*x=0;s->GetSession(j,&x);AudioSessionState st;if(x&&SUCCEEDED(x->GetState(&st))&&st==AudioSessionStateActive){LPWSTR name=0;x->GetDisplayName(&name);if(name&&wcsstr(name,L"Redmi Note 13 Pro+ 5G Hands-Free HF Audio"))found=true;if(name)CoTaskMemFree(name);}if(x)x->Release();}s->Release();}m->Release();}if(d)d->Release();}if(c)c->Release();return found;}
int wmain(int argc,wchar_t**argv){int seconds=8;if(argc==3&&!wcscmp(argv[1],L"--seconds"))seconds=_wtoi(argv[2]);if(seconds<1||seconds>20)return 2;if(FAILED(CoInitializeEx(0,COINIT_MULTITHREADED)))return 3;IMMDeviceEnumerator*e=0;CoCreateInstance(__uuidof(MMDeviceEnumerator),0,CLSCTX_ALL,IID_PPV_ARGS(&e));if(!e||!sentinel(e)){if(e)e->Release();CoUninitialize();return 4;}IMMDevice*d=0;HRESULT h=e->GetDefaultAudioEndpoint(eRender,eCommunications,&d);IAudioClient*a=0;IAudioCaptureClient*c=0;HANDLE ev=0;if(SUCCEEDED(h))h=d->Activate(__uuidof(IAudioClient),CLSCTX_ALL,0,(void**)&a);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=48000;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=192000;if(SUCCEEDED(h))h=a->Initialize(AUDCLNT_SHAREMODE_SHARED,AUDCLNT_STREAMFLAGS_LOOPBACK|AUDCLNT_STREAMFLAGS_EVENTCALLBACK|AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM,0,0,&f,0);if(SUCCEEDED(h))h=a->GetService(IID_PPV_ARGS(&c));ev=CreateEventW(0,FALSE,FALSE,0);if(SUCCEEDED(h)&&ev)h=a->SetEventHandle(ev);if(SUCCEEDED(h))h=a->Start();ULONGLONG end=GetTickCount64()+(ULONGLONG)seconds*1000;while(SUCCEEDED(h)&&GetTickCount64()<end){if(WaitForSingleObject(ev,100)!=WAIT_OBJECT_0)continue;UINT32 p=0;while(SUCCEEDED(c->GetNextPacketSize(&p))&&p){BYTE*x=0;UINT32 fr=0;DWORD fl=0;h=c->GetBuffer(&x,&fr,&fl,0,0);if(FAILED(h))break;size_t bytes=(size_t)fr*4;if(fl&AUDCLNT_BUFFERFLAGS_SILENT){std::vector<BYTE>z(bytes);fwrite(z.data(),1,bytes,stdout);}else fwrite(x,1,bytes,stdout);c->ReleaseBuffer(fr);p=0;}}if(a)a->Stop();if(ev)CloseHandle(ev);if(c)c->Release();if(a)a->Release();if(d)d->Release();if(e)e->Release();CoUninitialize();return FAILED(h)?5:0;}
