// Guarded endpoint-loopback diagnostic. This is explicitly SYSTEM_MIX_GUARDED, never process attribution.
#include <windows.h>
#include <mmdeviceapi.h>
#include <audioclient.h>
#include <audiopolicy.h>
#include <functiondiscoverykeys_devpkey.h>
#include <cstdio>
#include <cwchar>
#include <string>
#include <vector>
#include <cmath>

static std::string u8(const wchar_t*s){if(!s)return"";int n=WideCharToMultiByte(CP_UTF8,0,s,-1,0,0,0,0);std::string r(n,'\0');if(n){WideCharToMultiByte(CP_UTF8,0,s,-1,r.data(),n,0,0);r.pop_back();}return r;} static std::string esc(const std::string&s){std::string r;for(char c:s){if(c=='\\'||c=='\"'){r+='\\';r+=c;}else if(c=='\n')r+="\\n";else if(c=='\r')r+="\\r";else r+=c;}return r;}
struct M{unsigned long long n=0;long double q=0;int p=0;void add(BYTE*d,UINT32 f,UINT16 c){short*x=(short*)d;for(unsigned long long i=0,z=(unsigned long long)f*c;i<z;i++){int v=x[i],a=v<0?-v:v;if(a>p)p=a;q+=(long double)v*v;}n+=(unsigned long long)f*c;}double rms()const{return n?sqrt((double)(q/n)):0;}};
struct Session{std::string endpoint,name,process;DWORD pid;};
static std::string friendly(IMMDevice*d){IPropertyStore*s=0;PROPVARIANT v;PropVariantInit(&v);std::string n;if(SUCCEEDED(d->OpenPropertyStore(STGM_READ,&s))){if(SUCCEEDED(s->GetValue(PKEY_Device_FriendlyName,&v))&&v.vt==VT_LPWSTR)n=u8(v.pwszVal);s->Release();}PropVariantClear(&v);return n;}
static bool sessions(IMMDeviceEnumerator*en,std::vector<Session>&active){IMMDeviceCollection*c=0;en->EnumAudioEndpoints(eRender,DEVICE_STATEMASK_ALL,&c);UINT count=0;if(c)c->GetCount(&count);bool sentinel=false;for(UINT i=0;i<count;i++){IMMDevice*d=0;c->Item(i,&d);if(!d)continue;LPWSTR id=0;d->GetId(&id);IAudioSessionManager2*m=0;if(SUCCEEDED(d->Activate(__uuidof(IAudioSessionManager2),CLSCTX_ALL,0,(void**)&m))){IAudioSessionEnumerator*se=0;if(SUCCEEDED(m->GetSessionEnumerator(&se))){int sc=0;se->GetCount(&sc);for(int j=0;j<sc;j++){IAudioSessionControl*ctl=0;se->GetSession(j,&ctl);IAudioSessionControl2*c2=0;if(ctl&&SUCCEEDED(ctl->QueryInterface(IID_PPV_ARGS(&c2)))){AudioSessionState st;c2->GetState(&st);if(st==AudioSessionStateActive){LPWSTR dn=0;ctl->GetDisplayName(&dn);DWORD pid=0;c2->GetProcessId(&pid);std::string display=u8(dn);active.push_back({friendly(d),display,"",pid});if(display.find("Redmi Note 13 Pro+ 5G Hands-Free HF Audio")!=std::string::npos)sentinel=true;if(dn)CoTaskMemFree(dn);}c2->Release();}if(ctl)ctl->Release();}se->Release();}m->Release();}if(id)CoTaskMemFree(id);d->Release();}if(c)c->Release();return sentinel;}
struct Result{std::string role,name,id,error,wav;double duration=0;UINT32 rate=0;UINT16 channels=0;M m;};
static Result capture(IMMDeviceEnumerator*en,ERole role,const wchar_t*wav,double seconds){Result r;r.role=role==eCommunications?"communications":"console";r.wav=u8(wav);r.duration=seconds;IMMDevice*d=0;HRESULT h=en->GetDefaultAudioEndpoint(eRender,role,&d);if(FAILED(h)){r.error="default endpoint unavailable";return r;}LPWSTR id=0;d->GetId(&id);r.id=u8(id);r.name=friendly(d);IAudioClient*a=0;IAudioCaptureClient*c=0;HANDLE ev=0;FILE*f=0;if(FAILED(d->Activate(__uuidof(IAudioClient),CLSCTX_ALL,0,(void**)&a)))r.error="audio client activation";WAVEFORMATEX fmt{};if(r.error.empty()){fmt.wFormatTag=WAVE_FORMAT_PCM;fmt.nChannels=2;fmt.nSamplesPerSec=48000;fmt.wBitsPerSample=16;fmt.nBlockAlign=4;fmt.nAvgBytesPerSec=192000;h=a->Initialize(AUDCLNT_SHAREMODE_SHARED,AUDCLNT_STREAMFLAGS_LOOPBACK|AUDCLNT_STREAMFLAGS_EVENTCALLBACK|AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM,0,0,&fmt,0);if(FAILED(h))r.error="audio client initialize";else{r.rate=fmt.nSamplesPerSec;r.channels=fmt.nChannels;if(FAILED(a->GetService(IID_PPV_ARGS(&c))))r.error="capture service";}}if(r.error.empty()){ev=CreateEventW(0,FALSE,FALSE,0);if(!ev||FAILED(a->SetEventHandle(ev)))r.error="event setup";}if(r.error.empty()&&_wfopen_s(&f,wav,L"wb")!=0)r.error="wav open";if(r.error.empty()){DWORD z=0,fs=16;WORD pcm=1;fwrite("RIFF",1,4,f);fwrite(&z,4,1,f);fwrite("WAVEfmt ",1,8,f);fwrite(&fs,4,1,f);fwrite(&pcm,2,1,f);fwrite(&r.channels,2,1,f);fwrite(&r.rate,4,1,f);fwrite(&fmt.nAvgBytesPerSec,4,1,f);fwrite(&fmt.nBlockAlign,2,1,f);fwrite(&fmt.wBitsPerSample,2,1,f);fwrite("data",1,4,f);fwrite(&z,4,1,f);if(FAILED(a->Start()))r.error="start";}ULONGLONG end=GetTickCount64()+(ULONGLONG)(seconds*1000);while(r.error.empty()&&GetTickCount64()<end){if(WaitForSingleObject(ev,100)!=WAIT_OBJECT_0)continue;UINT32 p=0;while(SUCCEEDED(c->GetNextPacketSize(&p))&&p){BYTE*x=0;UINT32 fr=0;DWORD fl=0;if(FAILED(c->GetBuffer(&x,&fr,&fl,0,0))){r.error="get buffer";break;}size_t b=(size_t)fr*fmt.nBlockAlign;if(fl&AUDCLNT_BUFFERFLAGS_SILENT){std::vector<BYTE>z(b);fwrite(z.data(),1,b,f);r.m.n+=(unsigned long long)fr*r.channels;}else{fwrite(x,1,b,f);r.m.add(x,fr,r.channels);}c->ReleaseBuffer(fr);p=0;}}if(a)a->Stop();if(f){DWORD bytes=(DWORD)(r.m.n/r.channels*4),all=36+bytes;fseek(f,4,SEEK_SET);fwrite(&all,4,1,f);fseek(f,40,SEEK_SET);fwrite(&bytes,4,1,f);fclose(f);}if(ev)CloseHandle(ev);if(c)c->Release();if(a)a->Release();if(id)CoTaskMemFree(id);d->Release();return r;}
static void emitResult(const Result&r){bool signal=r.error.empty()&&r.m.n&&r.m.p>=100&&r.m.rms()>=20;printf("{\"role\":\"%s\",\"endpointName\":\"%s\",\"endpointId\":\"%s\",\"wav\":\"%s\",\"duration\":%.3f,\"sampleRate\":%u,\"channels\":%u,\"samples\":%llu,\"rms\":%.3f,\"peak\":%d,\"signal\":%s,\"error\":%s}",r.role.c_str(),esc(r.name).c_str(),esc(r.id).c_str(),esc(r.wav).c_str(),r.duration,r.rate,r.channels,r.m.n,r.m.rms(),r.m.p,signal?"true":"false",r.error.empty()?"null":("\""+esc(r.error)+"\"").c_str());}
int wmain(int argc,wchar_t**argv){double seconds=12;const wchar_t*wav=L"diagnostics\\guarded_system_mix_call.wav";bool noSentinel=false;for(int i=1;i<argc;i++){if(!wcscmp(argv[i],L"--seconds")&&i+1<argc)seconds=wcstod(argv[++i],0);else if(!wcscmp(argv[i],L"--wav")&&i+1<argc)wav=argv[++i];else if(!wcscmp(argv[i],L"--no-sentinel"))noSentinel=true;else return 2;}if(FAILED(CoInitializeEx(0,COINIT_MULTITHREADED)))return 1;IMMDeviceEnumerator*en=0;CoCreateInstance(__uuidof(MMDeviceEnumerator),0,CLSCTX_ALL,IID_PPV_ARGS(&en));std::vector<Session> active;bool sentinel=en&&sessions(en,active);if(!sentinel&&!noSentinel){printf("{\"state\":\"CALL_SENTINEL_NOT_ACTIVE\",\"attempts\":[]}");if(en)en->Release();CoUninitialize();return 1;}Result comm=capture(en,eCommunications,wav,seconds);Result con;IMMDevice*d=0;std::string consoleId;if(SUCCEEDED(en->GetDefaultAudioEndpoint(eRender,eConsole,&d))){LPWSTR id=0;d->GetId(&id);consoleId=u8(id);if(id)CoTaskMemFree(id);d->Release();}if(consoleId!=comm.id){std::wstring alt(wav);size_t dot=alt.rfind(L'.');alt.insert(dot==std::wstring::npos?alt.size():dot,L"_console");con=capture(en,eConsole,alt.c_str(),seconds);}printf("{\"state\":\"%s\",\"callSentinelActive\":%s,\"loopbackTap\":\"PRE_VOLUME_MUTE_DEFAULT\",\"otherActiveRenderSessions\":[",noSentinel?"VOLUME_TAP_PROBE":"GUARDED_SYSTEM_MIX_CANDIDATE",sentinel?"true":"false");for(size_t i=0;i<active.size();i++)printf("%s{\"endpointName\":\"%s\",\"displayName\":\"%s\",\"pid\":%lu}",i?",":"",esc(active[i].endpoint).c_str(),esc(active[i].name).c_str(),active[i].pid);printf("],\"attempts\":[");emitResult(comm);if(consoleId!=comm.id){printf(",");emitResult(con);}printf("]}\n");if(en)en->Release();CoUninitialize();return 0;}
