package org.scut.app;

import android.app.*;
import android.content.*;
import android.os.*;
import android.provider.Settings;
import android.graphics.Color;
import android.util.Base64;
import android.view.*;
import android.widget.TextView;
import org.json.JSONObject;
import java.io.*; import java.net.*; import java.security.*; import java.util.*;

public class ScutService extends Service {
 private static final String CHANNEL="scut_alerts"; private volatile Socket socket; private volatile BufferedWriter writer;
 @Override protected void attachBaseContext(Context base){super.attachBaseContext(LocaleHelper.apply(base));}
 @Override public void onCreate(){super.onCreate(); createChannel(); startForeground(1, notification(getString(R.string.notification_service_title), getString(R.string.notification_service_body))); new Thread(this::connectLoop,"scut-ws").start();}
 public static boolean pair(Context c,String endpoint,String token){ SharedPreferences p=c.getSharedPreferences("scut",Context.MODE_PRIVATE); CredentialStore.clearLocal(c); if(!CredentialStore.putPrivate(c,"pairToken",token))return false; p.edit().putString("endpoint",endpoint).apply(); Intent i=new Intent(c,ScutService.class); if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i); return true; }
 private void connectLoop(){ while(true){try{SharedPreferences p=getSharedPreferences("scut",MODE_PRIVATE);String endpoint=p.getString("endpoint","");if(endpoint.isEmpty()){Thread.sleep(2000);continue;} websocket(endpoint,CredentialStore.getLocal(this),CredentialStore.getPrivate(this,"pairToken"));}catch(Exception e){try{Thread.sleep(3000);}catch(InterruptedException ignored){return;}}}}
 private void websocket(String endpoint,String credential,String pairingToken)throws Exception{ URI uri=new URI(endpoint);socket=new Socket();socket.connect(new InetSocketAddress(uri.getHost(),uri.getPort()==-1?80:uri.getPort()),8000);InputStream in=socket.getInputStream();writer=new BufferedWriter(new OutputStreamWriter(socket.getOutputStream(),"UTF-8"));String key=Base64.encodeToString(UUID.randomUUID().toString().getBytes("UTF-8"),Base64.NO_WRAP);writer.write("GET "+(uri.getRawPath()==null?"/ws":uri.getRawPath())+" HTTP/1.1\r\nHost: "+uri.getHost()+"\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: "+key+"\r\nSec-WebSocket-Version: 13\r\n\r\n");writer.flush(); BufferedReader header=new BufferedReader(new InputStreamReader(in));String first=header.readLine();while(header.readLine()!=null&&!header.readLine().isEmpty()){} if(first==null||!first.contains("101"))throw new IOException("WebSocket rejected"); if(credential.isEmpty())send(new JSONObject().put("type","pair").put("token",pairingToken).put("device",Build.MANUFACTURER+" "+Build.MODEL).put("appVersion","1.0.0").put("permissions",permissions()));else send(new JSONObject().put("type","auth").put("credential",credential)); while(true){JSONObject m=read(in); if(m==null)return; if("paired".equals(m.optString("type"))){String localCredential=m.getString("credential");if(!CredentialStore.putLocal(this,localCredential))throw new IOException("Secure credential storage unavailable");CredentialStore.removePrivate(this,"pairToken");send(new JSONObject().put("type","auth").put("credential",localCredential));}if("authenticated".equals(m.optString("type"))){ new Handler(Looper.getMainLooper()).postDelayed(this::heartbeat,500); }if("alert".equals(m.optString("type"))){alert(m);send(new JSONObject().put("type","ack").put("alertId",m.optString("id")).put("sentMonotonic",m.optDouble("sentMonotonic")));}}}
 private JSONObject permissions()throws Exception{return new JSONObject().put("notifications",Build.VERSION.SDK_INT<33||checkSelfPermission("android.permission.POST_NOTIFICATIONS")==android.content.pm.PackageManager.PERMISSION_GRANTED).put("overlay",Settings.canDrawOverlays(this)).put("vibration",true).put("foregroundService",true);}
 private void heartbeat(){try{send(new JSONObject().put("type","heartbeat").put("permissions",permissions()));new Handler(Looper.getMainLooper()).postDelayed(this::heartbeat,10000);}catch(Exception ignored){}}
 private synchronized void send(JSONObject o)throws Exception{byte[] b=o.toString().getBytes("UTF-8");ByteArrayOutputStream f=new ByteArrayOutputStream();f.write(0x81);if(b.length<126)f.write(0x80|b.length);else{f.write(0xFE);f.write((b.length>>8)&255);f.write(b.length&255);}byte[] mask=new byte[4];new SecureRandom().nextBytes(mask);f.write(mask);for(int i=0;i<b.length;i++)f.write(b[i]^mask[i%4]);socket.getOutputStream().write(f.toByteArray());socket.getOutputStream().flush();}
 private JSONObject read(InputStream in)throws Exception{int a=in.read(),b=in.read();if(a<0||b<0)return null;int n=b&127;if(n==126)n=(in.read()<<8)|in.read();if(n>65536)throw new IOException("frame too large");byte[] d=new byte[n];int offset=0;while(offset<n){int read=in.read(d,offset,n-offset);if(read<0)throw new EOFException("incomplete frame");offset+=read;}return new JSONObject(new String(d,"UTF-8"));}
 private void alert(JSONObject m){Vibrator v=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(v!=null)v.vibrate(VibrationEffect.createWaveform(new long[]{0,500,180,500,180,700},-1));String message=m.optString("message",getString(R.string.alert_open_context));NotificationManager nm=getSystemService(NotificationManager.class);nm.notify(2,notification(getString(R.string.alert_possible_scam),message));if(Settings.canDrawOverlays(this))showOverlay(message);}
 private Notification notification(String title,String message){return new Notification.Builder(this,CHANNEL).setSmallIcon(R.drawable.ic_scut_notification).setColor(ScutUi.GREEN).setContentTitle(title).setContentText(message).setStyle(new Notification.BigTextStyle().bigText(message)).setPriority(Notification.PRIORITY_MAX).build();}
 private void createChannel(){NotificationChannel c=new NotificationChannel(CHANNEL,getString(R.string.notification_channel_service),NotificationManager.IMPORTANCE_HIGH);getSystemService(NotificationManager.class).createNotificationChannel(c);}
 private void showOverlay(String message){WindowManager wm=(WindowManager)getSystemService(WINDOW_SERVICE);TextView v=new TextView(this);v.setText(getString(R.string.overlay_alert_text,message));v.setTextColor(Color.rgb(30,33,27));v.setTextSize(20);v.setPadding(48,52,48,52);android.graphics.drawable.GradientDrawable background=new android.graphics.drawable.GradientDrawable();background.setColor(Color.rgb(250,248,242));background.setStroke(3,Color.rgb(166,76,65));v.setBackground(background);WindowManager.LayoutParams p=new WindowManager.LayoutParams(WindowManager.LayoutParams.MATCH_PARENT,WindowManager.LayoutParams.WRAP_CONTENT,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,android.graphics.PixelFormat.TRANSLUCENT);wm.addView(v,p);new Handler(Looper.getMainLooper()).postDelayed(()->{try{wm.removeView(v);}catch(Exception ignored){}},12000);}
 @Override public IBinder onBind(Intent i){return null;} @Override public void onDestroy(){try{if(socket!=null)socket.close();}catch(Exception ignored){}super.onDestroy();}
}
