import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type AppLanguage = 'en' | 'ru' | 'ro'

const en = {
  home: 'Home', history: 'History', alerts: 'Alerts', devices: 'Devices', settings: 'Settings',
  liveTranscript: 'Live transcript', dismiss: 'Dismiss notice', loadingTitle: 'Checking SCUT…',
  loadingBody: 'Reading the current protection state.', disconnectedTitle: 'SCUT is not connected', retry: 'Try again',
  historyEyebrow: 'Conversations', historyTitle: 'Conversation history', historyBody: 'Final transcripts synced securely from real SCUT call sessions.',
  historyEmpty: 'No conversations yet', historyEmptyBody: 'Completed call transcripts will appear here after SCUT receives stable speech.',
  alertsEyebrow: 'Safety', alertsTitle: 'Alerts', alertsBody: 'Warnings created by the existing SCUT incident pipeline.',
  alertsEmpty: 'No alerts yet', alertsEmptyBody: 'Safety warnings will appear here when a real incident is recorded.',
  offlineCached: 'Offline — showing the last synced data', loadMore: 'Load more', loading: 'Loading…', unavailable: 'Unavailable right now',
  possibleScam: 'Possible scam detected', alertCleared: 'Warning cleared', noTranscript: 'No final transcript was stored.',
  protectedPhone: 'Protected phone', unknownPhone: 'Protected device', duration: '{value} sec', openConversation: 'Open conversation',
  conversation: 'Conversation', transcript: 'Transcript', evidence: 'Why this stood out', contextLimited: 'No evidence excerpt is available.',
  deleteConversation: 'Delete conversation', deleteConfirm: 'Delete this conversation transcript on every SCUT device? Incident audit metadata will remain, with evidence redacted.',
  cancel: 'Cancel', delete: 'Delete', back: 'Back', deleted: 'Conversation deleted everywhere.',
  deviceHeading: 'Connected companion', deviceBody: 'A real Android companion heartbeat appears here when available.', device: 'Device', connection: 'Connection',
  connected: 'Connected', offline: 'Offline', noHeartbeat: 'No companion heartbeat', permissions: 'Permissions', notifications: 'Notifications', overlay: 'Safety overlay', vibration: 'Vibration', granted: 'Granted', needsPermission: 'Needs permission', available: 'Available',
  pairHeading: 'Local recovery pairing', pairBody: 'Create a one-time payload only when local recovery is needed.', createPairing: 'Create pairing payload', copy: 'Copy payload', pairingReady: 'Pairing payload is ready.', copied: 'Pairing payload copied.',
  settingsEyebrow: 'Preferences', settingsTitle: 'SCUT settings', settingsBody: 'Language and protection controls stay simple. Technical tools are kept in Advanced diagnostics.',
  language: 'Language', languageBody: 'Choose the interface language for this device.', english: 'English', russian: 'Русский', romanian: 'Română',
  protectionMode: 'Protection mode', current: 'Current: {value}', advanced: 'Advanced diagnostics', advancedBody: 'Local service status, tests and recovery tools for development or support.',
  serviceState: 'Control plane', serviceReason: 'Connection detail', decisionEpoch: 'Decision epoch', liveSession: 'Live call session',
  explicitTests: 'Explicit tests', diagnostics: 'Diagnostics', run: 'Run', analyzeText: 'Analyze stable text', analyze: 'Analyze locally', stableTranscript: 'Stable transcript',
  recording: 'Verified capture recording', loadRecording: 'Load recording', privateDefault: 'Private by default',
  homeLive: 'Live local state', currentBehavior: 'Current behavior', currentBehaviorBody: 'SCUT reports only what is ready now. It never assumes an active call.',
  systemOverview: 'System overview', currentSetup: 'Current setup', localSource: 'From the local SCUT service', audioPath: 'Audio path', companion: 'Companion', recentActivity: 'Recent activity',
  localPrivacy: 'Processing stays on this machine unless a configured provider is enabled.',
  evidenceLabel: 'Contextual evidence', decision: 'Decision', signal: 'Signal', requestedActions: 'Requested actions', close: 'Close',
  caller: 'Caller', you: 'You', final: 'Final', criticalSignal: 'Critical signal', emitted: 'Android alert signal emitted', emittedBody: 'The service emitted an alert event; delivery is not confirmed here.',
  liveLocalStream: 'Live local stream', reconnecting: 'Reconnecting local stream', streamUnavailable: 'Local stream unavailable', connecting: 'Connecting local stream', conversationLiveBody: 'Finalized caller speech from the local SCUT service.',
  protectionPaused:'Protection is paused',protectionPausedBody:"SCUT is open, but it isn't evaluating caller speech while protection is off.",testReady:'Test mode is ready',testReadyBody:'SCUT is available for explicit diagnostics. Continuous call protection is not running.',protectionOn:'Protection mode is on',protectionOnBody:'SCUT evaluates stable caller speech it receives. Capture readiness is shown separately.',modeOff:'Off',modeTest:'Test',modeProtect:'Protect',captureVerified:'Capture verified',captureVerifiedBody:'Phone Link audio was verified with {value}.',captureAttention:'Capture needs attention',captureAttentionBody:'The latest Phone Link capture check did not pass on this machine.',captureUnverified:'Capture unverified',captureUnverifiedBody:'Phone Link capture has not been verified on this machine.',companionOffline:'Android companion offline',companionOfflineBody:'No paired companion is connected right now.',companionConnected:'Android companion connected',companionConnectedBody:'{value} is responding to SCUT.',noRecent:'No recent activity',noRecentBody:'The local service has not reported a recent event.',protectionLabel:'Protection / {value}',protectionState:'Protection state',ready:'Ready',check:'Check',quiet:'Quiet',
  localService:'Local service',connectingService:'Connecting local service',reconnectingService:'Reconnecting local service',riskSignal:'Risk signal',listening:'Listening',listeningElapsed:'Listening / {value}',analysing:'Analysing final speech',openScut:'Open SCUT',
} as const

export type I18nKey = keyof typeof en
type Key = I18nKey
type Catalog = Record<Key, string>

const ru: Catalog = {
  home:'Главная',history:'История',alerts:'Оповещения',devices:'Устройства',settings:'Настройки',liveTranscript:'Текущая расшифровка',dismiss:'Закрыть сообщение',loadingTitle:'Проверяем SCUT…',loadingBody:'Получаем актуальное состояние защиты.',disconnectedTitle:'SCUT не подключён',retry:'Повторить',
  historyEyebrow:'Разговоры',historyTitle:'История разговоров',historyBody:'Финальные расшифровки реальных звонков, синхронизированные SCUT.',historyEmpty:'Разговоров пока нет',historyEmptyBody:'Завершённые расшифровки появятся после получения устойчивой речи.',alertsEyebrow:'Безопасность',alertsTitle:'Оповещения',alertsBody:'Предупреждения из действующего incident-контура SCUT.',alertsEmpty:'Оповещений пока нет',alertsEmptyBody:'Предупреждения появятся после регистрации реального инцидента.',offlineCached:'Нет сети — показаны последние синхронизированные данные',loadMore:'Показать ещё',loading:'Загрузка…',unavailable:'Сейчас недоступно',
  possibleScam:'Возможен мошеннический звонок',alertCleared:'Предупреждение снято',noTranscript:'Финальная расшифровка не сохранена.',protectedPhone:'Защищаемый телефон',unknownPhone:'Защищаемое устройство',duration:'{value} с',openConversation:'Открыть разговор',conversation:'Разговор',transcript:'Расшифровка',evidence:'Почему это важно',contextLimited:'Фрагмент доказательства недоступен.',deleteConversation:'Удалить разговор',deleteConfirm:'Удалить расшифровку разговора на всех устройствах SCUT? Метаданные аудита инцидента сохранятся, а доказательства будут скрыты.',cancel:'Отмена',delete:'Удалить',back:'Назад',deleted:'Разговор удалён на всех устройствах.',
  deviceHeading:'Подключённый помощник',deviceBody:'Здесь отображается реальный heartbeat Android-устройства.',device:'Устройство',connection:'Соединение',connected:'Подключено',offline:'Не в сети',noHeartbeat:'Нет heartbeat помощника',permissions:'Разрешения',notifications:'Уведомления',overlay:'Защитное окно',vibration:'Вибрация',granted:'Разрешено',needsPermission:'Нужно разрешение',available:'Доступно',pairHeading:'Локальное восстановление связи',pairBody:'Создавайте одноразовые данные только для восстановления локальной связи.',createPairing:'Создать данные подключения',copy:'Копировать',pairingReady:'Данные подключения готовы.',copied:'Данные подключения скопированы.',
  settingsEyebrow:'Параметры',settingsTitle:'Настройки SCUT',settingsBody:'Язык и защита остаются простыми. Технические инструменты находятся в расширенной диагностике.',language:'Язык',languageBody:'Выберите язык интерфейса этого устройства.',english:'English',russian:'Русский',romanian:'Română',protectionMode:'Режим защиты',current:'Текущий: {value}',advanced:'Расширенная диагностика',advancedBody:'Состояние локального сервиса, тесты и восстановление для разработки или поддержки.',serviceState:'Control plane',serviceReason:'Состояние соединения',decisionEpoch:'Эпоха решений',liveSession:'Активный звонок',explicitTests:'Явные тесты',diagnostics:'Диагностика',run:'Запустить',analyzeText:'Анализ устойчивого текста',analyze:'Анализировать локально',stableTranscript:'Устойчивая расшифровка',recording:'Проверенная запись захвата',loadRecording:'Загрузить запись',privateDefault:'Приватность по умолчанию',
  homeLive:'Локальное состояние',currentBehavior:'Текущее поведение',currentBehaviorBody:'SCUT сообщает только о фактически готовых функциях и не предполагает активный звонок.',systemOverview:'Обзор системы',currentSetup:'Текущая настройка',localSource:'По данным локального сервиса SCUT',audioPath:'Аудиоканал',companion:'Помощник',recentActivity:'Недавняя активность',localPrivacy:'Обработка остаётся на этом компьютере, если внешний провайдер не настроен.',evidenceLabel:'Контекстные признаки',decision:'Решение',signal:'Сигнал',requestedActions:'Запрошенные действия',close:'Закрыть',caller:'Собеседник',you:'Вы',final:'Финал',criticalSignal:'Критический сигнал',emitted:'Сигнал Android-оповещения отправлен',emittedBody:'Сервис создал событие оповещения; доставка здесь не подтверждается.',liveLocalStream:'Локальный поток',reconnecting:'Переподключение к потоку',streamUnavailable:'Локальный поток недоступен',connecting:'Подключение к потоку',conversationLiveBody:'Финальная речь собеседника из локального сервиса SCUT.',
  protectionPaused:'Защита приостановлена',protectionPausedBody:'SCUT открыт, но не анализирует речь собеседника, пока защита выключена.',testReady:'Тестовый режим готов',testReadyBody:'SCUT доступен для явной диагностики. Постоянная защита звонка не запущена.',protectionOn:'Режим защиты включён',protectionOnBody:'SCUT анализирует полученную устойчивую речь собеседника. Готовность захвата показана отдельно.',modeOff:'Выкл.',modeTest:'Тест',modeProtect:'Защита',captureVerified:'Захват проверен',captureVerifiedBody:'Аудио Phone Link проверено через {value}.',captureAttention:'Проверьте захват',captureAttentionBody:'Последняя проверка захвата Phone Link на этом компьютере не прошла.',captureUnverified:'Захват не проверен',captureUnverifiedBody:'Захват Phone Link на этом компьютере ещё не проверен.',companionOffline:'Android-помощник не в сети',companionOfflineBody:'Сейчас нет подключённого помощника.',companionConnected:'Android-помощник подключён',companionConnectedBody:'{value} отвечает SCUT.',noRecent:'Нет недавней активности',noRecentBody:'Локальный сервис ещё не сообщил о недавнем событии.',protectionLabel:'Защита / {value}',protectionState:'Состояние защиты',ready:'Готово',check:'Проверить',quiet:'Тихо',
  localService:'Локальный сервис',connectingService:'Подключение к локальному сервису',reconnectingService:'Переподключение к локальному сервису',riskSignal:'Сигнал риска',listening:'Слушаем',listeningElapsed:'Слушаем / {value}',analysing:'Анализируем финальную речь',openScut:'Открыть SCUT',
}

const ro: Catalog = {
  home:'Acasă',history:'Istoric',alerts:'Alerte',devices:'Dispozitive',settings:'Setări',liveTranscript:'Transcriere live',dismiss:'Închide mesajul',loadingTitle:'Se verifică SCUT…',loadingBody:'Se citește starea actuală de protecție.',disconnectedTitle:'SCUT nu este conectat',retry:'Încearcă din nou',
  historyEyebrow:'Conversații',historyTitle:'Istoricul conversațiilor',historyBody:'Transcrieri finale sincronizate din sesiuni SCUT reale.',historyEmpty:'Încă nu există conversații',historyEmptyBody:'Transcrierile finalizate vor apărea după ce SCUT primește vorbire stabilă.',alertsEyebrow:'Siguranță',alertsTitle:'Alerte',alertsBody:'Avertizări create de fluxul real de incidente SCUT.',alertsEmpty:'Încă nu există alerte',alertsEmptyBody:'Avertizările vor apărea când este înregistrat un incident real.',offlineCached:'Offline — sunt afișate ultimele date sincronizate',loadMore:'Încarcă mai multe',loading:'Se încarcă…',unavailable:'Indisponibil momentan',
  possibleScam:'Posibil apel fraudulos',alertCleared:'Avertizarea a fost anulată',noTranscript:'Nu a fost salvată nicio transcriere finală.',protectedPhone:'Telefon protejat',unknownPhone:'Dispozitiv protejat',duration:'{value} sec',openConversation:'Deschide conversația',conversation:'Conversație',transcript:'Transcriere',evidence:'De ce a atras atenția',contextLimited:'Fragmentul de context nu este disponibil.',deleteConversation:'Șterge conversația',deleteConfirm:'Ștergi transcrierea conversației pe toate dispozitivele SCUT? Metadatele de audit rămân, iar dovezile sunt redactate.',cancel:'Anulează',delete:'Șterge',back:'Înapoi',deleted:'Conversația a fost ștearsă pe toate dispozitivele.',
  deviceHeading:'Dispozitiv conectat',deviceBody:'Aici apare heartbeat-ul real al companionului Android.',device:'Dispozitiv',connection:'Conexiune',connected:'Conectat',offline:'Offline',noHeartbeat:'Niciun heartbeat de la companion',permissions:'Permisiuni',notifications:'Notificări',overlay:'Mesaj de siguranță',vibration:'Vibrație',granted:'Permis',needsPermission:'Necesită permisiune',available:'Disponibil',pairHeading:'Asociere locală de recuperare',pairBody:'Creează un payload de unică folosință doar când este necesară recuperarea locală.',createPairing:'Creează payload',copy:'Copiază',pairingReady:'Payload-ul de asociere este gata.',copied:'Payload-ul a fost copiat.',
  settingsEyebrow:'Preferințe',settingsTitle:'Setări SCUT',settingsBody:'Limba și protecția rămân simple. Instrumentele tehnice sunt în diagnosticarea avansată.',language:'Limbă',languageBody:'Alege limba interfeței pentru acest dispozitiv.',english:'English',russian:'Русский',romanian:'Română',protectionMode:'Mod de protecție',current:'Curent: {value}',advanced:'Diagnosticare avansată',advancedBody:'Starea serviciului local, teste și recuperare pentru dezvoltare sau suport.',serviceState:'Plan de control',serviceReason:'Detaliu conexiune',decisionEpoch:'Epoca deciziei',liveSession:'Sesiune activă',explicitTests:'Teste explicite',diagnostics:'Diagnosticare',run:'Rulează',analyzeText:'Analizează text stabil',analyze:'Analizează local',stableTranscript:'Transcriere stabilă',recording:'Înregistrare verificată',loadRecording:'Încarcă înregistrarea',privateDefault:'Confidențial implicit',
  homeLive:'Stare locală live',currentBehavior:'Comportament curent',currentBehaviorBody:'SCUT raportează doar ce este pregătit acum și nu presupune un apel activ.',systemOverview:'Prezentare sistem',currentSetup:'Configurație curentă',localSource:'Din serviciul local SCUT',audioPath:'Cale audio',companion:'Companion',recentActivity:'Activitate recentă',localPrivacy:'Procesarea rămâne pe acest computer dacă nu este activat un furnizor configurat.',evidenceLabel:'Dovezi contextuale',decision:'Decizie',signal:'Semnal',requestedActions:'Acțiuni solicitate',close:'Închide',caller:'Apelant',you:'Tu',final:'Final',criticalSignal:'Semnal critic',emitted:'Semnalul alertei Android a fost emis',emittedBody:'Serviciul a emis alerta; livrarea nu este confirmată aici.',liveLocalStream:'Flux local live',reconnecting:'Reconectare la fluxul local',streamUnavailable:'Flux local indisponibil',connecting:'Conectare la fluxul local',conversationLiveBody:'Vorbirea finalizată a apelantului din serviciul local SCUT.',
  protectionPaused:'Protecția este oprită',protectionPausedBody:'SCUT este deschis, dar nu evaluează vorbirea apelantului cât timp protecția este oprită.',testReady:'Modul test este pregătit',testReadyBody:'SCUT este disponibil pentru diagnosticare explicită. Protecția continuă nu rulează.',protectionOn:'Modul de protecție este activ',protectionOnBody:'SCUT evaluează vorbirea stabilă primită. Starea capturii este afișată separat.',modeOff:'Oprit',modeTest:'Test',modeProtect:'Protecție',captureVerified:'Captură verificată',captureVerifiedBody:'Sunetul Phone Link a fost verificat cu {value}.',captureAttention:'Captura necesită atenție',captureAttentionBody:'Ultima verificare Phone Link nu a reușit pe acest computer.',captureUnverified:'Captură neverificată',captureUnverifiedBody:'Captura Phone Link nu a fost încă verificată pe acest computer.',companionOffline:'Companionul Android este offline',companionOfflineBody:'Niciun companion asociat nu este conectat acum.',companionConnected:'Companionul Android este conectat',companionConnectedBody:'{value} răspunde către SCUT.',noRecent:'Nicio activitate recentă',noRecentBody:'Serviciul local nu a raportat un eveniment recent.',protectionLabel:'Protecție / {value}',protectionState:'Starea protecției',ready:'Pregătit',check:'Verifică',quiet:'Liniștit',
  localService:'Serviciu local',connectingService:'Conectare la serviciul local',reconnectingService:'Reconectare la serviciul local',riskSignal:'Semnal de risc',listening:'Ascultare',listeningElapsed:'Ascultare / {value}',analysing:'Se analizează vorbirea finală',openScut:'Deschide SCUT',
}

const catalogs: Record<AppLanguage, Catalog> = { en, ru, ro }
export type Translator = (key: Key, values?: Record<string, string | number>) => string
type I18n = { language: AppLanguage; setLanguage(value: AppLanguage): void; t: Translator }
const Context = createContext<I18n | null>(null)
const fallback: I18n = { language: 'en', setLanguage: () => undefined, t: (key, values) => {
  let value: string = en[key]
  for (const [name, replacement] of Object.entries(values ?? {})) value = value.replaceAll(`{${name}}`, String(replacement))
  return value
} }

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<AppLanguage>(() => {
    const requested = new URLSearchParams(window.location.search).get('lang')
    if (requested === 'ru' || requested === 'ro' || requested === 'en') return requested
    const saved = localStorage.getItem('scut-language')
    return saved === 'ru' || saved === 'ro' || saved === 'en' ? saved : 'en'
  })
  useEffect(() => { localStorage.setItem('scut-language', language); document.documentElement.lang = language }, [language])
  const value = useMemo<I18n>(() => ({ language, setLanguage, t: (key, values) => {
    let text: string = catalogs[language][key]
    for (const [name, replacement] of Object.entries(values ?? {})) text = text.replaceAll(`{${name}}`, String(replacement))
    return text
  } }), [language])
  return <Context.Provider value={value}>{children}</Context.Provider>
}

export function useI18n(): I18n {
  const value = useContext(Context)
  return value ?? fallback
}
